apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: mongodb
  namespace: cozy-system
spec:
  application:
    kind: MongoDB
    openAPISchema: |
      {
        "title": "MongoDB options",
        "type": "object",
        "properties": {
          "architecture": {
            "type": "string",
            "enum": ["standalone", "replicaset"],
            "default": "replicaset",
            "description": "Deployment architecture for MongoDB."
          },
          "replicaCount": {
            "type": "integer",
            "minimum": 1,
            "default": 3,
            "description": "Number of MongoDB replicas (replica set only)."
          },
          "replicaSetName": {
            "type": "string",
            "default": "",
            "description": "Optional replica set name; falls back to the release name."
          },
          "arbiter": {
            "type": "object",
            "properties": {
              "enabled": {
                "type": "boolean",
                "default": false,
                "description": "Deploy an arbiter node to break ties in the replica set."
              }
            }
          },
          "auth": {
            "type": "object",
            "properties": {
              "enabled": {
                "type": "boolean",
                "default": true,
                "description": "Enable SCRAM authentication."
              },
              "rootUser": {
                "type": "string",
                "default": "root",
                "description": "Admin user name."
              },
              "rootPassword": {
                "type": "string",
                "default": "",
                "description": "Admin password. Required unless an existingSecret is provided."
              },
              "username": {
                "type": "string",
                "default": "",
                "description": "Optional application user."
              },
              "password": {
                "type": "string",
                "default": "",
                "description": "Password for the optional application user."
              },
              "database": {
                "type": "string",
                "default": "",
                "description": "Database granted to the optional application user."
              },
              "replicaSetKey": {
                "type": "string",
                "default": "",
                "description": "Replica set keyfile value for intra-node authentication."
              },
              "existingSecret": {
                "type": "string",
                "default": "",
                "description": "Secret containing mongodb-root-password and mongodb-replica-set-key keys."
              }
            }
          },
          "persistence": {
            "type": "object",
            "properties": {
              "enabled": {
                "type": "boolean",
                "default": true,
                "description": "Persist MongoDB data to volumes."
              },
              "size": {
                "type": "string",
                "default": "20Gi",
                "description": "Volume size for each MongoDB pod."
              },
              "storageClass": {
                "type": "string",
                "default": "",
                "description": "StorageClass to use; empty uses the cluster default."
              },
              "accessModes": {
                "type": "array",
                "items": { "type": "string" },
                "default": ["ReadWriteOnce"],
                "description": "PVC access modes."
              }
            }
          },
          "service": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "default": "ClusterIP",
                "description": "Service type for exposing MongoDB."
              },
              "port": {
                "type": "integer",
                "default": 27017,
                "description": "MongoDB service port."
              }
            }
          },
          "resources": {
            "type": "object",
            "properties": {
              "requests": {
                "type": "object",
                "properties": {
                  "cpu": { "type": "string", "default": "250m" },
                  "memory": { "type": "string", "default": "512Mi" }
                }
              },
              "limits": {
                "type": "object",
                "properties": {
                  "cpu": { "type": "string", "default": "1000m" },
                  "memory": { "type": "string", "default": "2Gi" }
                }
              }
            },
            "description": "Resource requests and limits for MongoDB pods."
          },
          "tls": {
            "type": "object",
            "properties": {
              "enabled": {
                "type": "boolean",
                "default": false,
                "description": "Enable TLS for MongoDB connections."
              },
              "autoGenerated": {
                "type": "boolean",
                "default": true,
                "description": "Create self-signed certificates when no secret is provided."
              },
              "existingSecret": {
                "type": "string",
                "default": "",
                "description": "TLS secret to reuse instead of generating certificates."
              }
            }
          },
          "metrics": {
            "type": "object",
            "properties": {
              "enabled": {
                "type": "boolean",
                "default": true,
                "description": "Enable MongoDB metrics exporter."
              },
              "serviceMonitor": {
                "type": "object",
                "properties": {
                  "enabled": {
                    "type": "boolean",
                    "default": false,
                    "description": "Create a ServiceMonitor for Prometheus Operator."
                  },
                  "namespace": {
                    "type": "string",
                    "default": "",
                    "description": "Namespace where the ServiceMonitor should live."
                  },
                  "interval": {
                    "type": "string",
                    "default": "30s",
                    "description": "Scrape interval for the ServiceMonitor."
                  }
                }
              }
            }
          }
        }
      }
    plural: mongodbs
    singular: mongodb
  release:
    chart:
      name: ./packages/apps/mongodb
      sourceRef:
        kind: GitRepository
        name: external-apps
        namespace: cozy-public
    labels:
      cozystack.io/ui: "true"
    prefix: mongodb-
  dashboard:
    category: PaaS
    singular: MongoDB
    plural: MongoDB
    description: MongoDB is a popular NoSQL database.
    tags:
      - database
    icon: PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTIwLjU4NSAyMy4xODVDMjAuNTg1IDIyLjcwNiAyMC4zODUgMjIuMjk3IDIwLjA0NSAyMS45NzVDMTguMTc1IDIwLjE1NSAxNi43NDUgMTcuNDY1IDE2LjI4NSAxNS42NDVDMTYuMjc1IDE1LjYyNSAxNi4yNzUgMTUuNjA1IDE2LjI2NSAxNS41ODVDMTYuMjY1IDEuNTc1IDE2LjI2NSAxNS41NjUgMTYuMjY1IDE1LjU0NUwxNi4xMDUgMTQuOTA1IDE1LjkwNSAxNC4yNTUgMTUuNzA1IDEzLjY3NSAxNC44MjUgMTEuMDk1IDE0LjE2NSA5LjE3NSAxMy40NTUgNy43NjVDMTMuMzA1IDE1Ljc0NSAxNC45ODUgMTcuNTA1IDE3LjE2NSAxOC4zMzVDMTcuMzA1IDE4LjM4NSAxNy41MDUgMTguNDQ1IDE3LjcwNSAxOC40OTVMMTcuNzA1IDIxLjk3N0MyMC4yNjUgMjQuNDk1IDIzLjQ1NSAyMy4zNDUgMjMuNDU1IDIzLjM0NUwyMC41ODUgMjMuMTg1WiIgZmlsbD0iMDgwQTUzIi8+Cjwvc3ZnPg==
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: vault
  namespace: cozy-system
spec:
  application:
    kind: Vault
    openAPISchema: |
      {
        "title": "Vault options",
        "type": "object",
        "properties": {
          "vault": {
            "type": "object",
            "properties": {
              "nameOverride": {
                "type": "string",
                "default": "",
                "description": "Override the chart name for resource naming."
              },
              "fullnameOverride": {
                "type": "string",
                "default": "",
                "description": "Override the full release name."
              },
              "server": {
                "type": "object",
                "properties": {
                  "ha": {
                    "type": "object",
                    "properties": {
                      "enabled": { "type": "boolean", "default": true },
                      "replicas": { "type": "integer", "minimum": 1, "default": 3 },
                      "raft": {
                        "type": "object",
                        "properties": {
                          "enabled": { "type": "boolean", "default": true },
                          "setNodeId": { "type": "boolean", "default": true },
                          "config": {
                            "type": "string",
                            "default": "ui = true\nlistener \\\"tcp\\\" {\n  address = \\\"[::]:8200\\\"\n  cluster_address = \\\"[::]:8201\\\"\n  tls_disable = \\\"true\\\"\n}\nstorage \\\"raft\\\" {\n  path = \\\"/vault/data\\\"\n}\nservice_registration \\\"kubernetes\\\" {}\n"
                          }
                        }
                      }
                    }
                  },
                  "dataStorage": {
                    "type": "object",
                    "properties": {
                      "enabled": { "type": "boolean", "default": true },
                      "size": { "type": "string", "default": "20Gi" },
                      "storageClass": { "type": "string", "default": "" },
                      "accessMode": { "type": "string", "default": "ReadWriteOnce" }
                    }
                  },
                  "auditStorage": {
                    "type": "object",
                    "properties": {
                      "enabled": { "type": "boolean", "default": false },
                      "size": { "type": "string", "default": "10Gi" },
                      "storageClass": { "type": "string", "default": "" },
                      "accessMode": { "type": "string", "default": "ReadWriteOnce" }
                    }
                  },
                  "service": {
                    "type": "object",
                    "properties": {
                      "enabled": { "type": "boolean", "default": true },
                      "type": { "type": "string", "default": "ClusterIP" },
                      "port": { "type": "integer", "default": 8200 }
                    }
                  },
                  "ingress": {
                    "type": "object",
                    "properties": {
                      "enabled": { "type": "boolean", "default": false },
                      "ingressClassName": { "type": "string", "default": "" },
                      "annotations": { "type": "object", "additionalProperties": { "type": "string" }, "default": {} },
                      "hosts": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "host": { "type": "string" },
                            "paths": {
                              "type": "array",
                              "items": {
                                "type": "object",
                                "properties": {
                                  "path": { "type": "string", "default": "/" },
                                  "pathType": { "type": "string", "default": "Prefix" }
                                }
                              },
                              "default": []
                            }
                          },
                          "required": ["host"]
                        },
                        "default": []
                      },
                      "tls": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "hosts": { "type": "array", "items": { "type": "string" }, "default": [] },
                            "secretName": { "type": "string", "default": "" }
                          }
                        },
                        "default": []
                      }
                    }
                  },
                  "resources": {
                    "type": "object",
                    "properties": {
                      "requests": {
                        "type": "object",
                        "properties": {
                          "cpu": { "type": "string", "default": "500m" },
                          "memory": { "type": "string", "default": "1Gi" }
                        }
                      },
                      "limits": {
                        "type": "object",
                        "properties": {
                          "cpu": { "type": "string", "default": "1" },
                          "memory": { "type": "string", "default": "2Gi" }
                        }
                      }
                    }
                  },
                  "nodeSelector": { "type": "object", "additionalProperties": { "type": "string" }, "default": {} },
                  "tolerations": { "type": "array", "items": { "type": "object" }, "default": [] },
                  "affinity": { "type": "object", "default": {} },
                  "extraEnvironmentVars": {
                    "type": "array",
                    "items": { "type": "object", "properties": { "name": { "type": "string" }, "value": { "type": "string" } }, "required": ["name", "value"] },
                    "default": []
                  },
                  "extraVolumes": { "type": "array", "items": { "type": "object" }, "default": [] },
                  "extraVolumeMounts": { "type": "array", "items": { "type": "object" }, "default": [] }
                }
              },
              "injector": {
                "type": "object",
                "properties": {
                  "enabled": { "type": "boolean", "default": true },
                  "replicas": { "type": "integer", "minimum": 1, "default": 1 },
                  "webhook": { "type": "object", "properties": { "failurePolicy": { "type": "string", "default": "Ignore" } } },
                  "resources": {
                    "type": "object",
                    "properties": {
                      "requests": { "type": "object", "properties": { "cpu": { "type": "string", "default": "100m" }, "memory": { "type": "string", "default": "128Mi" } } },
                      "limits": { "type": "object", "properties": { "cpu": { "type": "string", "default": "500m" }, "memory": { "type": "string", "default": "256Mi" } } }
                    }
                  }
                }
              },
              "csi": {
                "type": "object",
                "properties": {
                  "enabled": { "type": "boolean", "default": false },
                  "driver": { "type": "object", "properties": { "name": { "type": "string", "default": "secrets.csi.k8s.io" } } },
                  "agent": { "type": "object", "properties": { "replicas": { "type": "integer", "minimum": 1, "default": 1 } } }
                }
              }
            }
          }
        }
      }
    plural: vaults
    singular: vault
  release:
    chart:
      name: ./packages/apps/vault
      sourceRef:
        kind: GitRepository
        name: external-apps
        namespace: cozy-public
    labels:
      cozystack.io/ui: "true"
    prefix: vault-
  dashboard:
    category: Security
    singular: Vault
    plural: Vault
    description: HashiCorp Vault for secure secret management.
    tags:
      - security
      - secrets
    icon: PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHJ4PSI2IiBmaWxsPSIjMjg1M0Y2Ii8+PHBhdGggZD0iTTE0LjMzMyAxMC42NjZjMC0uNzc5LjYzLTEuNDA2IDEuNDA1LTEuNDA2aDEuNTMzYy43NzUgMCAxLjQwNS42MjcgMS40MDUgMS40MDZ2MS42NjloMS42NmMuNzc2IDAgMS40MDYuNjI3IDEuNDA2IDEuNDA2djEuNTMzYzAgLjc3OS0uNjMgMS40MDYtMS40MDYgMS40MDZoLTEuNjZ2MS42NkMxOS4zMzMgMjQuMzcyIDE4LjcwMyAyNSA5LjkyMyAyNWgtMS41MzNjLS43NzUgMC0xLjQwNS0uNjI4LTEuNDA1LTEuNDA2di0xLjY2aC0xLjY2Yy0uNzc1IDAtMS40MDUtLjYyNy0xLjQwNS0xLjQwNnYtMS41MzNjMC0uNzc5LjYzLTEuNDA2IDEuNDA1LTEuNDA2aDEuNjZ2LTEuNjY2eiIgZmlsbD0iI0ZGRiIvPjwvc3ZnPg==
