---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: cozy-system
spec:
  interval: 30m
  url: https://charts.bitnami.com/bitnami

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-catalog
  namespace: cozy-system
  labels:
    cozystack.io/application: "true"
    cozystack.io/type: "helm"
data:
  name: "MongoDB"
  displayName: "MongoDB Database"
  description: "MongoDB NoSQL database with persistence"
  category: "Databases"
  icon: "https://www.mongodb.com/assets/images/global/favicon.ico"
  helmChart: "mongodb"
  helmRepo: "bitnami"
  helmVersion: "16.x.x"
  defaultValues: |
    auth:
      enabled: true
      rootPassword: ""
      database: "mydb"
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
