apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-app-metadata
  namespace: cozy-system
  labels:
    cozystack.io/application: "true"
data:
  name: "MongoDB"
  description: "MongoDB NoSQL Database"
  category: "Databases"
  icon: "https://www.mongodb.com/assets/images/global/favicon.ico"
